# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 21:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(default='', max_length=20, verbose_name='小说的频道')),
            ],
            options={
                'verbose_name': '频道管理',
                'verbose_name_plural': '频道管理',
                'db_table': 'Channel',
            },
        ),
        migrations.CreateModel(
            name='NovelChaPter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novelchapter_name', models.CharField(max_length=30, verbose_name='章节名称')),
                ('novelchapter_text', models.TextField(verbose_name='章节内容')),
                ('novelchapter_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='章节更新时间')),
            ],
            options={
                'verbose_name': '章节管理',
                'verbose_name_plural': '章节管理',
                'db_table': 'NovelChaPter',
            },
        ),
        migrations.CreateModel(
            name='NovelModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('novel_name', models.CharField(max_length=30, verbose_name='小说的名称')),
                ('novel_image', models.ImageField(blank=True, null=True, upload_to='novel/%Y/%m', verbose_name='小说的封面图')),
                ('novel_byte', models.IntegerField(default=0, verbose_name='字节数')),
                ('novel_read', models.IntegerField(default=0, verbose_name='阅读量')),
                ('novel_comment', models.IntegerField(default=0, verbose_name='评论量')),
                ('novel_text', models.TextField(max_length=200, verbose_name='小说的简介')),
                ('novel_fave', models.IntegerField(default=0, verbose_name='小说的收藏数')),
                ('novel_next', models.IntegerField(default=0, verbose_name='浏览量')),
                ('novel_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='小说更新时间')),
            ],
            options={
                'verbose_name': '小说管理',
                'verbose_name_plural': '小说管理',
                'db_table': 'NovelModel',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=20, verbose_name='小说的类别')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Channel', verbose_name='小说的频道')),
            ],
            options={
                'verbose_name': '类别管理',
                'verbose_name_plural': '类别管理',
                'db_table': 'TagModel',
            },
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='novel_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.TagModel', verbose_name='小说的类别'),
        ),
    ]
