# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('novel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='novel_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProFile', verbose_name='小说的作者'),
        ),
        migrations.AddField(
            model_name='novelchapter',
            name='novelchapter_cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelModel', verbose_name='所属小说'),
        ),
    ]
