# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0002_auto_20180108_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='is_long',
            field=models.BooleanField(default=True, verbose_name='是否登录可读'),
        ),
    ]
