# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 22:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0003_novelmodel_is_long'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '标签合集',
                'verbose_name_plural': '标签合集',
                'db_table': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Tage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签管理',
                'verbose_name_plural': '标签管理',
                'db_table': 'Tage',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.Tage', verbose_name='标签合集'),
        ),
    ]
