# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0004_auto_20180109_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
    ]
