# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0007_tage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tage',
            options={'verbose_name': '添加标签', 'verbose_name_plural': '添加标签'},
        ),
        migrations.AddField(
            model_name='novelmodel',
            name='novel_tage',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.Tage', verbose_name='添加标签'),
        ),
        migrations.AlterField(
            model_name='tage',
            name='tag_name',
            field=taggit.managers.TaggableManager(help_text='输入标签以空格或者,作为分隔符', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
