# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 23:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0008_auto_20180109_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='novelmodel',
            name='novel_tage',
        ),
    ]
