# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 23:07
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('novel', '0009_remove_novelmodel_novel_tage'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='novel_tage',
            field=taggit.managers.TaggableManager(help_text='输入标签以空格或者,作为分隔符', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='标签选择'),
        ),
    ]
