# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0010_novelmodel_novel_tage'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapter',
            name='novelchapter_num',
            field=models.IntegerField(default=0, verbose_name='章节数'),
        ),
    ]
