# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 11:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0011_novelchapter_novelchapter_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexAdView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adTitle', models.CharField(default='', max_length=20, verbose_name='广告标题')),
                ('adImage', models.ImageField(max_length=200, upload_to='ad/%Y/%m', verbose_name='广告图片')),
                ('adText', models.CharField(default='', max_length=100, verbose_name='广告简介')),
                ('addtime', models.TimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '广告管理',
                'verbose_name_plural': '广告管理',
                'db_table': 'IndexAdView',
            },
        ),
    ]
