# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0012_indexadview'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexadview',
            name='adUrl',
            field=models.URLField(default='', max_length=100, verbose_name='广告url'),
        ),
    ]
