# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0014_auto_20180112_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexadview',
            name='adImage',
            field=models.ImageField(blank=True, null=True, upload_to='addimg/%Y/%m', verbose_name='小说的封面图'),
        ),
    ]
