# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 12:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0016_auto_20180112_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novelmodel',
            name='novel_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='小说的名称'),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='novel_tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='novel.TagModel', verbose_name='小说的类别'),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='novel_text',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='小说的简介'),
        ),
        migrations.AlterField(
            model_name='novelmodel',
            name='novel_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.UserProFile', verbose_name='小说的作者'),
        ),
    ]
