# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-16 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0017_auto_20180113_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelmodel',
            name='novel_alias',
            field=models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='小说的别名'),
        ),
    ]
