# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-08 23:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readnovel',
            name='novel_id',
        ),
        migrations.RemoveField(
            model_name='readnovel',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='readnovel',
            name='novel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelModel', verbose_name='小说'),
        ),
        migrations.AlterField(
            model_name='readnovel',
            name='novel_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='阅读时间'),
        ),
        migrations.AlterField(
            model_name='readnovel',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProFile', verbose_name='户名'),
        ),
    ]
