# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 21:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180109_0103'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sign_bool',
            field=models.BooleanField(default=False, verbose_name='签约'),
        ),
    ]
