# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-09 22:18
from __future__ import unicode_literals

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_sign_bool'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingUser',
            fields=[
            ],
            options={
                'verbose_name': '签约作者',
                'verbose_name_plural': '签约作者',
                'proxy': True,
                'indexes': [],
            },
            bases=('users.userprofile',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='adminpro',
            options={'verbose_name': '管理信息', 'verbose_name_plural': '管理信息'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '普通用户', 'verbose_name_plural': '普通用户'},
        ),
    ]
