# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180109_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='readnovel',
            name='chapter_num',
            field=models.IntegerField(default=0, verbose_name='小说的章节ID'),
        ),
    ]
