# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 14:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_readnovel_chapter_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0, verbose_name='用户ID')),
                ('book_id', models.IntegerField(default=0, verbose_name='小说ID')),
                ('comment', models.CharField(max_length=200, verbose_name='评论内容')),
                ('comment_data', models.DateTimeField(default=datetime.datetime.now, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '用户评论',
                'verbose_name_plural': '用户评论',
                'db_table': 'CommentModels',
            },
        ),
    ]
