# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180110_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodels',
            name='book_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelModel', verbose_name='小说'),
        ),
        migrations.AlterField(
            model_name='commentmodels',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProFile', verbose_name='用户'),
        ),
    ]
