# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_commentmodels_commtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='novel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelModel', verbose_name='小说ID'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProFile', verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='readnovel',
            name='novel_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelModel', verbose_name='小说ID'),
        ),
        migrations.AlterField(
            model_name='readnovel',
            name='user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserProFile', verbose_name='用户ID'),
        ),
    ]
