# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0011_novelchapter_novelchapter_num'),
        ('users', '0013_auto_20180110_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auth', models.CharField(max_length=40, verbose_name='昵称')),
                ('contents', models.TextField(max_length=2000, verbose_name='内容')),
                ('time', models.TimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novel.NovelModel')),
            ],
        ),
    ]
