# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-11 21:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_blogcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcontent',
            name='blog',
        ),
        migrations.DeleteModel(
            name='BlogContent',
        ),
    ]
